## 0. Pytorch fundamentals

In [7]:
import torch
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.0


## 0.1 Intro to tensorss

In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

How to get scalar out of datatype.

In [11]:
scalar.item()

7

In [13]:
vector = torch.tensor([6,7])
vector

tensor([6, 7])

In [14]:
vector.ndim

1

In [18]:
matrix = torch.tensor([[1, 2],
                       [3, 5]])


In [16]:
matrix.ndim

2

In [17]:
matrix

tensor([[1, 2],
        [3, 5]])

In [21]:
matrix[0]

tensor([1, 2])

In [28]:
TENSOR = torch.tensor([[[1, 3, 4], [2, 4, 4]],
                       [[1, 3, 4], [2, 3, 4]]])


In [26]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([2, 2, 3])

## Random tensor

> Why?

Are important to create input data for NN

`Start with random num -> look at data -> update numbers -> look at data .... `

In [34]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4240, 0.5740, 0.3672, 0.3860],
        [0.8211, 0.7032, 0.2906, 0.0191],
        [0.0813, 0.6552, 0.7587, 0.6036]])

In [ ]:
# create random tensor with similar shape to image

random_image_tensor = torch.rand((224, 224, 3))